sudo: false

language: python

fast_finish: true

    env:
      global:
        # Doctr deploy key for GuQiangJS/stock_ai
        - secure: "BeWIdb515+uxJoODQt22c5L3XQPSGXodNp7CaOCOk7cQ4VCoQ87StGA0fBu/8agZGr0dDDIumZ9QPDerVz9jYIb48mVgb6ccxeSpN8ZYrIgniNPRtEV3ahvqwEHhkYsRKcSW4U9vATKifQStyX0IDTBhXj5tYTtkxK08p1Eya9vQeTBXogQrWiZoIKALgOk3ISLDEHm8ZGFuaiuT6RKhUz2jd9+InwZbnvCGPC+NK0FVLzEtYuwZfa+IAInCLKTScbFvmMc/oDj1K3WqnBuEFeTLREFypMG8oIVh/zXPz1M3Uc+MjvcKLZM/LNMyKx9d+y6ifipK2rOn5lBngQK3IM8oeVJSL6qQzMQ7OnwIMIFb/nv95adV0dOlQlt/srXysNHnb5X48sZJk2K5gzewMUKmHlAUMFb181tqWbSJiJq+IRIYnzJG89/ExLXzlNqda/AqUpbS8hKGgo60nQ9gYxclcJ8oepsKf26BC9c8BJzeJS+P5MK9dG9SFndbDA4FSqKH359ifVvk82yFJ5cS+myIuEXSopNFN2FZa8EzV5IbyZWAiqErmtcfIcCkactV+IYBl0WDzjIaPg4wQRYSgWxbfnq7BRpJT0Z9Mf3wbHyjh187t36rbGuwsQM2HNAMDU4JKTMgE4mMViGvhxmzKvw6VhlAG1mVOwTwP9XFGAU="

python:
  - "3.6"

matrix:
  include:
    - python: '3.6'
      env: DOCBUILD=true


install:
  - pip install QUANTAXIS
  - pip install --upgrade tensorflow
  - pip install coverage
  - if [[ $DOCBUILD ]]; then
    pip install sphinx sphinx_rtd_theme doctr sphinxcontrib-napoleon;
    fi
script:
  - coverage run -m unittest discover stock_ai "test_*.py"
after_success:
  - coverage report
  - |
    if [[ $DOCBUILD ]]; then
      cd docs
      make html && make html
      cd ..
      doctr deploy devel --build-tags
    fi
  - coveralls